# https://docs.readthedocs.com/platform/stable/build-customization.html
# This is currently deploying a static site, so just copy HTML files

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3"
  jobs:
    build:
      html:
        - mkdir -p $READTHEDOCS_OUTPUT/html
        - cp -r docs/* $READTHEDOCS_OUTPUT/html/
